# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fileservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/fileservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/fileservice.proto\x12\x0b\x66ileservice\"\x14\n\x04path\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x18\n\x03\x64ir\x12\x11\n\tfilenames\x18\x01 \x03(\t2?\n\x0c\x66ile_service\x12/\n\x08list_dir\x12\x11.fileservice.path\x1a\x10.fileservice.dirB\x14Z\x12grpc-seminar/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fileservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022grpc-seminar/proto'
  _globals['_PATH']._serialized_start=40
  _globals['_PATH']._serialized_end=60
  _globals['_DIR']._serialized_start=62
  _globals['_DIR']._serialized_end=86
  _globals['_FILE_SERVICE']._serialized_start=88
  _globals['_FILE_SERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
